### ISSUE TITLE
How to prevent window scroll while we're handling touch events on the X axis

### ISSUE THREAD

**Issue by Magellol** [pmndrs/react-use-gesture#216]
Hi 👋 

I've been building a simple slideshow and it all works great except that on iOS, if the movement is more of a diagonal between x/y or better said if the touch is "enough" on the y axis, the window would scroll at the same time. It's actually the same on the "Useful extras" examples https://use-gesture.netlify.app/docs/extras/ if open on iOS, we can drag and scroll the page at the same time.

I've tried many things like, overflow, body-scroll-lock, touch-action etc and nothing seems to be doing it. Any recommendations? Thanks!

I've uploaded an example here https://imgur.com/a/neJ3TBR

The implementation looks a bit like

```ts
const memo = React.useRef(0);

const gestures = useDrag(
    ({ down, swipe: [xSwipe], args: [state], movement: [xMovement], distance }) => {
      const xTotalDistance = window.innerWidth;

      if (down) {
        set(i => ({
          xsc: [memo.current + xMovement, state.card === i ? 0.95 : 0.98],
        }));
      } else if (Math.abs(distance) > 0.25 * xTotalDistance) {
        const isLeftSwipe = xMovement < 0;
        if (isLeftSwipe) {
          set({
            xsc: [memo.current - xTotalDistance, 1],
            immediate: false,
          });

          memo.current = memo.current - xTotalDistance;
        } else {
          set({
            xsc: [memo.current + xTotalDistance, 1],
            immediate: false,
          });

          memo.current = memo.current + xTotalDistance;
        }
      } else {
        set({ xsc: [memo.current, 1], immediate: false });
      }
    },
    { lockDirection: 'x', axis: 'x' },
  );
```

**Comment by dbismut** [comment]
Yes I had spotted the issue a while ago but wasn't sure what could be done about it. I'll have another look at it tomorrow and will suggest some possible directions if I find something useful. Cheers.

**Comment by Magellol** [comment]
@dbismut Awesome. I'm honestly a bit lost having tried many things already. Let me know what you find, I'm still thinking about it too. I feel it hurts the UX a lot in my opinion.

**Comment by dbismut** [comment]
@Magellol It's not an easy problem, but have a look at https://codesandbox.io/s/cranky-fast-mcst8.

The issue is still there (although less visible).

The main issue here is that there are two conflicting logics: our useDrag `axis` logic, that tries to determine the drag axis based on the comparison of `x` and `y` displacements (essentially as soon as `x > y` then the axis is horizontal), and the `touch-action` logic handled by the browser, which is certainly very superior to the useDrag logic, but is unfortunately a black box for us.

So the sandbox I've shared does two things that should be mentioned.

1. It uses react-use-gesture v8 in alpha which only deals with PointerEvents, and because of how pointer events work, the drag gesture gets canceled as soon as a scroll is registered, so you should never be in the situation that you've shared.

2. It uses the `threshold: [40, 0]` option. Essentially it tells `useDrag` that any displacement greater than `0` on the `y` axis is intentional, while only displacements greater than `40` on the `x` axis should trigger the gesture.

Because I believe the way the browser detects the intentionality is not solely based on the displacement (possibly also speed), there are still ways to fool that example. But I hope it does solve your problem, at least partially. Let me know.

PS: The API with active / last is a bit confusing so I think I'll make it a bit simpler before the official release of v8.

**Comment by Magellol** [comment]
@dbismut Woaw. By just switching to react-use-gesture@8, it seemed to already have fixed that issue. Perhaps because of what you said about using `PointerEvents`. In addition with the threshold, the experience is much better now.

Thank you for sending some pointers. What does `if (last === false && active === false) return;` do exactly?

**Comment by dbismut** [comment]
> Thank you for sending some pointers. What does `if (!last && !active) return;` do exactly?

So this is directly related to the PS in my last message, and it's a bit boring to explain. But essentially in v7, when options like `axis` or `threshold` were used, your handler would only fire when the gesture was detected as intentional.

So to give you an example, if you set `threshold: 40` in the options, your handler wouldn't be triggered until you would reach a displacement of `40`. The problem is that in certain situations, you **need** to access the first event such as `pointerdown` to `preventDefault` or `stopPropagation`. Because your handler wasn't fire until the gesture was considered intentional, you would not have access to these events.

So in v8, all events are now passed to your handler, but if you use intention-related options (again, `axis`, `threshold`, `filterTaps`), you need to make sure that your gesture logic is only triggers when the gesture is intentional.

The line `if (!last && !active) return;` makes sure that your logic only triggers when your gesture is intentional (`active=true`), or when your intentional gesture ends (`last=true, active=false`). What I'll probably do is either set a new flag like `intentional` that stays true even when the gesture ends, or an option like `{ allEvents: true }` that you need to set to get non intentional events. I still need to decide what's the best!

Makes sense?
