### ISSUE TITLE
useDrag position returns to [0, 0] before applying spring

### ISSUE THREAD

**Issue by austinmayer** [pmndrs/react-use-gesture#229]
When attempting to position a mesh with r3f and then apply a drag gesture, the drag interaction always returns to [0, 0] _before_ applying the spring animation. The initial interaction is disconnected on mouseDown with subsequent drags working fine after the position gets set. An initial spring position set via inbound props doesn't seem to solve. 

What am I missing? Could this be solved with `initial` as a drag option?

https://codesandbox.io/s/r3f-basic-demo-forked-rpgie?file=/src/App.js

**Comment by dbismut** [comment]
@austinmayer interesting problem thanks!

Here is a version using 8.1.0-alpha.12 which introduces transform, but I understand it's not totally mature (I'm disabling filterTaps for example, which is not ideal).

https://codesandbox.io/s/r3f-basic-demo-forked-h1dus?file=/src/App.js

I'll work on something to make use-gesture working in a different space coordinates easier.

**Comment by austinmayer** [comment]
@dbismut thanks! 

Transform looks like a great solve. Makes sense re: filterTaps at the moment.

**Comment by dbismut** [comment]
@austinmayer fixed now in 8.1.0-beta.2 (I suck at numbering versions and I want to release this soon in the wild anyway).
https://codesandbox.io/s/r3f-basic-demo-forked-h1dus?file=/src/App.js

Btw, make sure to have a `if(tap)` condition statement if you're using the `filterTaps` option. In general, you want to avoid setting drag position when the user only tapped as the drag isn't intentional (with the current logic there's no harm, but just saying FYI).

**Comment by austinmayer** [comment]
Amazing. Unreal how quick you turned this around, much appreciated!

And thanks for the tap improvements, this is great.

🙏🙏🙏

**Comment by dbismut** [comment]
Well I also fixed a couple of bugs I hadn't realized until playing with your sandbox so thanks to you too. I'll leave the issue open until 8.1.0 is actually released.
