### ISSUE TITLE
useDrag/usePinch collision on touchscreens

### ISSUE THREAD

**Issue by n1ru4l** [pmndrs/react-use-gesture#240]
https://codesandbox.io/s/react-three-fiber-react-use-drag-ux9w5

It seems like after removing one finger from the iPad during a pinch gesture a drag gesture is triggered.

**Comment by dbismut** [comment]
Hi @n1ru4l I don't think it can be considered as a bug as drag and pinch can happen at the same time and although I understand your use case, you could imagine a situation where users want to drag *and* pinch and be notified when either of the gestures end.

So I think the logic you want should be kept in user land, it's up to you to cancel the drag gesture when pinch starts and handle the cancellation so that no further drag logic is triggered during / just after a pinch. 

That being said, I've noticed several problems with the latest beta with how pinch is triggered, especially when pinch starts on nested children. I'll focus on this for now, but I'll keep your use case in mind and will try to see how it can be implemented in a practical way.

**Comment by n1ru4l** [comment]
Then it would definitely be nice to give an example of how something like that can be addressed in user-land, as I think this will be a pretty common issue people will run into 😇

**Comment by dbismut** [comment]
Here you go: https://codesandbox.io/s/boring-hertz-sokxs

**Comment by stephenhmarsh** [comment]
thank you so much for the example.  someone should add this to the docs.
